import type { AppData, AtsRecord } from '../types';

const now = '2024-05-19T08:45:00+09:00';

export const dummyRecords: AtsRecord[] = [
  { id: 'ats-001', name: 'Yuliana Magai', nik: '910205********4321', gender: 'Perempuan', birthDate: '2010-08-14', regency: 'Mimika', district: 'Kuala Kencana', village: 'Iwaka', lastEducation: 'SMP', lastClass: 'Kelas 2', dropoutYear: 2024, dropoutReason: 'Faktor Ekonomi', familyEconomic: 'Rentan', parentName: 'Daniel Magai', contact: '081245110001', verificationStatus: 'Terverifikasi', interventionStatus: 'Pendekatan Keluarga', officerName: 'Maria M.', createdAt: now, synced: true, latitude: -4.438, longitude: 136.884, notes: 'Perlu pendekatan keluarga dan bantuan biaya transportasi.' },
  { id: 'ats-002', name: 'Nataniel Wonda', nik: '910102********5678', gender: 'Laki-laki', birthDate: '2011-01-21', regency: 'Nabire', district: 'Nabire', village: 'Karang Mulia', lastEducation: 'SD', lastClass: 'Kelas 6', dropoutYear: 2024, dropoutReason: 'Bekerja', familyEconomic: 'Menengah bawah', parentName: 'Yosina Wonda', contact: '081245110002', verificationStatus: 'Terverifikasi', interventionStatus: 'Proses Intervensi', officerName: 'Yonas Tabuni', createdAt: '2024-05-19T07:20:00+09:00', synced: true, latitude: -3.366, longitude: 135.496, notes: 'Anak membantu keluarga bekerja harian.' },
  { id: 'ats-003', name: 'Melkianus Gobai', nik: '910309********6789', gender: 'Laki-laki', birthDate: '2010-05-09', regency: 'Paniai', district: 'Enarotali', village: 'Madi', lastEducation: 'SMP', lastClass: 'Kelas 1', dropoutYear: 2023, dropoutReason: 'Jarak & Transportasi', familyEconomic: 'Rentan', parentName: 'Petrus Gobai', contact: '081245110003', verificationStatus: 'Belum Diverifikasi', interventionStatus: 'Identifikasi Awal', officerName: 'Petrus Kobak', createdAt: '2024-05-18T16:10:00+09:00', synced: true, latitude: -3.92, longitude: 136.34, notes: 'Perlu verifikasi lokasi dan akses sekolah terdekat.' },
  { id: 'ats-004', name: 'Agustina Yogi', nik: '910407********2345', gender: 'Perempuan', birthDate: '2009-03-01', regency: 'Intan Jaya', district: 'Sugapa', village: 'Bilogai', lastEducation: 'Tidak Sekolah', lastClass: '-', dropoutYear: 2022, dropoutReason: 'Tidak Ada Sekolah', familyEconomic: 'Rentan', parentName: 'Maria Yogi', contact: '081245110004', verificationStatus: 'Terverifikasi', interventionStatus: 'Rujukan Layanan', officerName: 'Maria M.', createdAt: '2024-05-18T13:30:00+09:00', synced: true, latitude: -3.72, longitude: 136.67, notes: 'Rujukan layanan pendidikan nonformal.' },
  { id: 'ats-005', name: 'Yosepina Murib', nik: '910511********3456', gender: 'Perempuan', birthDate: '2012-09-11', regency: 'Dogiyai', district: 'Kamuu', village: 'Mowanemani', lastEducation: 'SD', lastClass: 'Kelas 5', dropoutYear: 2024, dropoutReason: 'Faktor Ekonomi', familyEconomic: 'Sangat rentan', parentName: 'Yosef Murib', contact: '081245110005', verificationStatus: 'Belum Diverifikasi', interventionStatus: 'Pendekatan Keluarga', officerName: 'Yonas Tabuni', createdAt: '2024-05-18T09:05:00+09:00', synced: false, latitude: -4.03, longitude: 135.93, notes: 'Data dari mode offline belum sinkron.' },
  { id: 'ats-006', name: 'Mikael Pigai', nik: '910612********1452', gender: 'Laki-laki', birthDate: '2008-11-20', regency: 'Deiyai', district: 'Tigi', village: 'Waghete', lastEducation: 'SMP', lastClass: 'Kelas 3', dropoutYear: 2023, dropoutReason: 'Minat & Motivasi', familyEconomic: 'Menengah bawah', parentName: 'Elis Pigai', contact: '081245110006', verificationStatus: 'Perlu Revisi', interventionStatus: 'Identifikasi Awal', officerName: 'Petrus Kobak', createdAt: '2024-04-22T10:30:00+09:00', synced: true, latitude: -4.04, longitude: 136.27, notes: 'Nomor kontak wali perlu diperbarui.' },
  { id: 'ats-007', name: 'Anastasia Kogoya', nik: '910708********7788', gender: 'Perempuan', birthDate: '2010-12-02', regency: 'Puncak Jaya', district: 'Mulia', village: 'Pagaleme', lastEducation: 'SMP', lastClass: 'Kelas 2', dropoutYear: 2022, dropoutReason: 'Menikah', familyEconomic: 'Rentan', parentName: 'Titus Kogoya', contact: '081245110007', verificationStatus: 'Terverifikasi', interventionStatus: 'Kembali Sekolah', officerName: 'Maria M.', createdAt: '2024-03-10T15:42:00+09:00', synced: true, latitude: -3.71, longitude: 137.99, notes: 'Sudah kembali sekolah melalui program pendampingan.' },
  { id: 'ats-008', name: 'Yakobus Tabuni', nik: '910805********6677', gender: 'Laki-laki', birthDate: '2011-02-18', regency: 'Mimika', district: 'Tembagapura', village: 'Banti', lastEducation: 'SD', lastClass: 'Kelas 4', dropoutYear: 2024, dropoutReason: 'Jarak & Transportasi', familyEconomic: 'Rentan', parentName: 'Stefanus Tabuni', contact: '081245110008', verificationStatus: 'Duplikat', interventionStatus: 'Identifikasi Awal', officerName: 'Yonas Tabuni', createdAt: '2024-02-27T11:30:00+09:00', synced: true, latitude: -4.05, longitude: 137.13, notes: 'Terdeteksi NIK mirip dengan data sebelumnya.' },
  { id: 'ats-009', name: 'Martha Wandikbo', nik: '910902********5512', gender: 'Perempuan', birthDate: '2009-06-25', regency: 'Paniai', district: 'Bogobaida', village: 'Kebo', lastEducation: 'SMP', lastClass: 'Kelas 1', dropoutYear: 2024, dropoutReason: 'Bekerja', familyEconomic: 'Menengah bawah', parentName: 'Obet Wandikbo', contact: '081245110009', verificationStatus: 'Terverifikasi', interventionStatus: 'Proses Intervensi', officerName: 'Petrus Kobak', createdAt: '2024-01-21T12:10:00+09:00', synced: true, latitude: -3.91, longitude: 136.22, notes: 'Dalam pendampingan agar masuk Paket B.' },
  { id: 'ats-010', name: 'Yustinus Kadepa', nik: '911006********4319', gender: 'Laki-laki', birthDate: '2012-04-12', regency: 'Nabire', district: 'Wanggar', village: 'Wiraska', lastEducation: 'SD', lastClass: 'Kelas 3', dropoutYear: 2024, dropoutReason: 'Faktor Ekonomi', familyEconomic: 'Sangat rentan', parentName: 'Lukas Kadepa', contact: '081245110010', verificationStatus: 'Terverifikasi', interventionStatus: 'Rujukan Layanan', officerName: 'Maria M.', createdAt: '2023-12-20T08:15:00+09:00', synced: false, latitude: -3.25, longitude: 135.42, notes: 'Butuh rujukan bantuan sosial pendidikan.' }
];

export const seedData: AppData = {
  records: dummyRecords,
  officers: [
    { id: 'ofc-001', name: 'Maria M.', role: 'Petugas Validasi', regency: 'Mimika', district: 'Kuala Kencana', phone: '081245221001', visits: 42, verified: 38, syncPending: 4, status: 'Aktif' },
    { id: 'ofc-002', name: 'Yonas Tabuni', role: 'Koordinator Lapangan', regency: 'Nabire', district: 'Nabire', phone: '081245221002', visits: 37, verified: 32, syncPending: 12, status: 'Aktif' },
    { id: 'ofc-003', name: 'Petrus Kobak', role: 'Petugas Lapangan', regency: 'Paniai', district: 'Enarotali', phone: '081245221003', visits: 29, verified: 24, syncPending: 8, status: 'Offline' },
    { id: 'ofc-004', name: 'Agnes Yogi', role: 'Petugas Lapangan', regency: 'Intan Jaya', district: 'Sugapa', phone: '081245221004', visits: 18, verified: 16, syncPending: 2, status: 'Cuti' }
  ],
  tasks: [
    { id: 'tsk-001', title: 'Pendekatan keluarga', location: 'Mimika - Distrik Kuala Kencana', atsCount: 15, dueLabel: 'Hari ini', priority: 'Hari ini', status: 'Aktif' },
    { id: 'tsk-002', title: 'Verifikasi data lapangan', location: 'Nabire - Distrik Nabire', atsCount: 8, dueLabel: 'Besok', priority: 'Besok', status: 'Aktif' },
    { id: 'tsk-003', title: 'Rapat koordinasi intervensi', location: 'Paniai - Distrik Enarotali', atsCount: 20, dueLabel: '20 Mei', priority: '20 Mei', status: 'Aktif' }
  ],
  alerts: [
    { id: 'alt-001', title: 'Duplikasi NIK', message: 'Terdeteksi 23 data dengan duplikasi NIK', timeLabel: '2 jam yang lalu', tone: 'warning', status: 'Unread' },
    { id: 'alt-002', title: 'Data belum ditindaklanjuti', message: '156 data ATS belum ada tindak lanjut', timeLabel: '5 jam yang lalu', tone: 'danger', status: 'Unread' },
    { id: 'alt-003', title: 'Sinkronisasi pending', message: '342 data lapangan belum tersinkron', timeLabel: '1 hari yang lalu', tone: 'info', status: 'Unread' }
  ],
  users: [
    { id: 'usr-001', name: 'Yohanis Tabuni, S.Pd', email: 'admin@papuatengah.go.id', role: 'Admin Provinsi', wilayah: 'Papua Tengah', status: 'Aktif' },
    { id: 'usr-002', name: 'Maria M.', email: 'maria.petugas@papuatengah.go.id', role: 'Petugas Lapangan', wilayah: 'Mimika', status: 'Aktif' },
    { id: 'usr-003', name: 'Yonas Tabuni', email: 'yonas.petugas@papuatengah.go.id', role: 'Petugas Lapangan', wilayah: 'Nabire', status: 'Aktif' },
    { id: 'usr-004', name: 'Kepala Dinas Pendidikan', email: 'kadis@papuatengah.go.id', role: 'Kepala Dinas', wilayah: 'Papua Tengah', status: 'Aktif' }
  ]
};
